# Generated by Django 5.1.7 on 2025-04-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_insightdata_added_alter_insightdata_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightdata',
            name='intensity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insightdata',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insightdata',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insightdata',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
