# Generated by Django 5.2 on 2025-04-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_insightdata_intensity_alter_insightdata_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightdata',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
