# Generated by Django 5.2 on 2025-04-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_insightdata_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightdata',
            name='swot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
