# Generated by Django 5.2 on 2025-04-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_insightdata_swot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightdata',
            name='intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insightdata',
            name='likelihood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insightdata',
            name='relevance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
